export const demoProducts = [
  { slug:'whey-isolate-pro', name:'Whey Isolate Pro', brand:'WarungFit Labs', category:'Protein', categorySlug:'protein', short:'25 g protein, rendah gula, rasa creamy.', description:'Protein isolate praktis untuk membantu memenuhi kebutuhan protein harian setelah latihan.', price:389000, compareAt:429000, featured:true, image:'/images/whey.svg', ingredients:'Whey protein isolate, cocoa powder, perisa, sukralosa.', directions:'Campurkan 1 scoop dengan 200–250 ml air.', nutrition:{'Takaran saji':'32 g','Protein':'25 g','Karbohidrat':'3 g','Kalori':'121 kkal'}, variants:[['WFI-CHO-1KG','Chocolate 1 kg','Chocolate',389000,24,1000],['WFI-VAN-1KG','Vanilla 1 kg','Vanilla',389000,15,1000]] },
  { slug:'creatine-monohydrate-300g', name:'Creatine Monohydrate', brand:'WarungFit Labs', category:'Performance', categorySlug:'performance', short:'Creatine murni tanpa rasa, 60 servings.', description:'Creatine monohydrate micronized untuk mendukung performa latihan intensitas tinggi.', price:179000, compareAt:199000, featured:true, image:'/images/creatine.svg', ingredients:'100% creatine monohydrate micronized.', directions:'Campurkan 5 g dengan air, satu kali sehari.', nutrition:{'Takaran saji':'5 g','Creatine':'5 g','Kalori':'0 kkal'}, variants:[['CRM-300','Unflavoured 300 g','Tanpa rasa',179000,31,300]] },
  { slug:'pre-workout-pump', name:'Pre-Workout Pump', brand:'Volt Nutrition', category:'Pre-Workout', categorySlug:'pre-workout', short:'Formula energi dan fokus untuk sesi berat.', description:'Kombinasi citrulline, beta alanine, dan kafein untuk digunakan sebelum latihan.', price:249000, compareAt:null, featured:true, image:'/images/preworkout.svg', ingredients:'L-citrulline, beta alanine, caffeine, taurine, perisa.', directions:'Campurkan 1 scoop dengan 250 ml air, 20–30 menit sebelum latihan.', nutrition:{'Takaran saji':'8 g','Kafein':'180 mg','Citrulline':'3000 mg'}, variants:[['PWO-TRP-250','Tropical Punch','Tropical',249000,11,250],['PWO-BRY-250','Mixed Berry','Berry',249000,8,250]] },
  { slug:'mass-gainer-ultimate', name:'Mass Gainer Ultimate', brand:'BulkForge', category:'Mass Gainer', categorySlug:'mass-gainer', short:'Kalori tinggi untuk membantu fase bulking.', description:'Perpaduan protein dan karbohidrat untuk membantu menambah asupan kalori harian.', price:459000, compareAt:499000, featured:false, image:'/images/gainer.svg', ingredients:'Maltodextrin, whey concentrate, oat powder, cocoa.', directions:'Campurkan 2 scoop dengan 400–500 ml air atau susu.', nutrition:{'Takaran saji':'150 g','Protein':'35 g','Kalori':'560 kkal'}, variants:[['MGU-CHO-3KG','Chocolate 3 kg','Chocolate',459000,9,3000]] },
  { slug:'bcaa-recovery', name:'BCAA Recovery', brand:'WarungFit Labs', category:'Amino', categorySlug:'amino', short:'BCAA 2:1:1 rasa lemon menyegarkan.', description:'Branched-chain amino acids untuk menemani sesi latihan.', price:199000, compareAt:null, featured:false, image:'/images/bcaa.svg', ingredients:'L-leucine, L-isoleucine, L-valine, citric acid.', directions:'Campurkan 1 scoop dengan 350 ml air.', nutrition:{'Takaran saji':'9 g','BCAA':'6000 mg'}, variants:[['BCAA-LEM-270','Lemon 270 g','Lemon',199000,18,270]] },
  { slug:'omega-3-fish-oil', name:'Omega-3 Fish Oil', brand:'PureDaily', category:'Wellness', categorySlug:'wellness', short:'Omega-3 harian dengan EPA dan DHA.', description:'Kapsul minyak ikan sebagai pelengkap pola makan seimbang.', price:129000, compareAt:null, featured:false, image:'/images/omega.svg', ingredients:'Fish oil concentrate, gelatin, glycerin.', directions:'Konsumsi 1 softgel dua kali sehari setelah makan.', nutrition:{'Takaran saji':'1 softgel','Fish oil':'1000 mg','EPA':'180 mg','DHA':'120 mg'}, variants:[['O3-90','90 Softgels',null,129000,42,120]] },
  { slug:'shaker-bottle-pro', name:'Shaker Bottle Pro', brand:'WarungFit Gear', category:'Accessories', categorySlug:'accessories', short:'Shaker anti-bocor 700 ml dengan mixing ball.', description:'Botol shaker BPA-free, praktis, dan mudah dibersihkan.', price:79000, compareAt:99000, featured:true, image:'/images/shaker.svg', ingredients:null, directions:null, nutrition:null, variants:[['SHK-BLK-700','Black 700 ml',null,79000,27,180],['SHK-LIME-700','Lime 700 ml',null,79000,19,180]] },
  { slug:'protein-bar-box', name:'Protein Bar Box', brand:'LeanBite', category:'Healthy Snack', categorySlug:'healthy-snack', short:'Camilan tinggi protein, box isi 12 bar.', description:'Protein bar praktis dengan tekstur chewy dan rasa chocolate almond.', price:219000, compareAt:null, featured:false, image:'/images/bar.svg', ingredients:'Milk protein, oats, almond, cocoa, inulin.', directions:'Konsumsi sebagai camilan sesuai kebutuhan.', nutrition:{'Takaran saji':'1 bar','Protein':'20 g','Kalori':'220 kkal'}, variants:[['PBR-CHO-12','Chocolate Almond (12 pcs)','Chocolate',219000,14,720]] }
];
